version: "3.8"

services:
  api:
    container_name: api
    build: ./API/startup-POC
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/poc_db
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - front
      - back
  web:
    container_name: web
    build: ./WEB
    depends_on:
      - db
      - api
    ports:
      - "8082:8082"
    networks:
      - front
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
